---

- name: Test ansible
  shell: sudo touch test_ansible

- name: Clear /var/run/ceph
  shell: sudo rm -r /var/run/ceph
  args:
    removes: /var/run/ceph

- name: Clear /var/lib/ceph/mds
  shell: sudo rm -r /var/lib/ceph/mds
  args:
    removes: /var/lib/ceph/mds

- name: Delete config directory
  shell: sudo rm -r /etc/ceph/
  args:
    removes: /etc/ceph/

- name: Create dir /etc/ceph/
  shell: sudo mkdir /etc/ceph/

- name: Change own to ceph /etc/ceph/
  shell: sudo chown -R ceph /etc/ceph/

- name: Change group to ceph /etc/ceph/
  shell: sudo chgrp -R ceph /etc/ceph/

- name: Clear keyring
  shell: sudo rm /etc/ceph/ceph.client.admin.keyring
  args:
    removes: /etc/ceph/ceph.client.admin.keyring

- name: Copy keyring file from mon node
  shell: sudo cp ceph.client.admin.keyring /etc/ceph/

- name: Delete old repo
  shell: sudo rm -rf Tiramisu
  args:
    removes: Tiramisu/this_is_dev_branch

- name: Clone ceph source code
  shell: git clone --recursive https://github.com/SOUP-CE-KMITL/Tiramisu.git --branch develop

- name: Copy service file
  shell: sudo cp Tiramisu/systemd/* /usr/lib/systemd/system/

- name: Change own for repo
  shell: sudo chown -R ceph Tiramisu

- name: Change group for repo
  shell: sudo chgrp -R ceph Tiramisu

- name: Install 3rd dependencies
  shell: sudo yum -y install {{ item }}
  with_items:
    - snappy
    - leveldb
    - gdisk
    - python-argparse
    - python-ceph
    - gperftools-libs
    - autoconf-archive

- name: Install dependencies
  shell: ./install-deps.sh
  args:
    chdir: Tiramisu

- name: Build autogen
  shell: ./autogen.sh
  args:
    chdir: Tiramisu/ 

- name: Build config
  shell: ./configure 
  args:
    chdir: Tiramisu

- name: Build make
  shell: sudo make -j4
  args:
    chdir: Tiramisu

- name: Install ceph
  shell: sudo make install
  args:
    chdir: Tiramisu

- name: Copy ceph.conf
  template: src=ceph_1_mon.conf.j2 dest=/etc/ceph/ceph.conf

- name: Change own to ceph /etc/ceph/
  shell: sudo chown -R ceph /etc/ceph/

- name: Change group to ceph /etc/ceph/
  shell: sudo chgrp -R ceph /etc/ceph/
         
- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/ceph* /usr/lib/python2.7/site-packages/
  
- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/rados* /usr/lib/python2.7/site-packages/

- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/rbd* /usr/lib/python2.7/site-packages/

- name: Stop old mds
  shell: sudo systemctl stop ceph-mds@{{ id }}
  ignore_errors: yes

- name: Delete old cephfs_data pool
  shell: ceph osd pool delete cephfs_data cephfs_data --yes-i-really-really-mean-it
  ignore_errors: yes

- name: Delete old cephfs_metadata pool
  shell: ceph osd pool delete cephfs_metadata cephfs_metadata --yes-i-really-really-mean-it
  ignore_errors: yes

- name: Romove old file system
  shell: ceph fs rm ceph_fs

- name: Remove old mds
  shell: ceph mds rm mds.{{ id }}
  ignore_errors: yes

- name: Create directory mds ceph-node
  shell: sudo mkdir -p /var/lib/ceph/mds/mds.{{ id }}

- name: Change permission lib ceph
  shell: sudo chmod -R 777 /var/lib/ceph/mds/mds.{{ id }}/

- name: Create keyring
  shell: sudo /usr/local/bin/ceph auth get-or-create mds.{{ id }} mds 'allow ' osd 'allow *' mon 'allow rwx' > /var/lib/ceph/mds/mds.{{ id }}/keyring

- name: Create /var/run/ceph
  shell: sudo mkdir /var/run/ceph

- name: Change permission lib ceph
  shell: sudo chmod -R 777 /var/lib/ceph/mds/mds.{{ id }}/

- name: Change permission run ceph
  shell: sudo chmod -R 777 /var/run/ceph/

- name: Reload daemon
  shell: sudo systemctl daemon-reload

- name: Start mds service
  shell: sudo systemctl restart ceph-mds@{{ id }}
